//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public System.DateTime DateBooked { get; set; }
        public decimal Price { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Payment Payments { get; set; }
        public virtual Customer Customers { get; set; }
        public virtual ExtrabedBooking ExtrabedBooking { get; set; }
    }
}
